title: Martin Devecka
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Martin Devecka
  email: mdevecka@ucsc.edu

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"


exclude: ['sitemap.xml','feed.xml', 'LICENSE', 'README.md']
